name: ChatManager
main: ChatManager.ChatManager
version: 1.0
description: Chat Manager which introduces Chat Channels and Messaging commands
author: Brandon
commands:
   msg:
      usage: /msg <player>
   channel:
      usage: /channel