name: MultiChat
main: com.caved_in.chatmanager.ChatManager
version: 1.0
description: An intuitive take to chat channels which is light-weight and customizable
author: Brandon (TheGamersCave)
commands:
   channel:
      usage: /channel
   prefix:
      usage: /prefix <ChatPrefix>
   namecolor:
      usage: /namecolor <colorcode>